### ISSUE TITLE
Update for Vapor 2?

### ISSUE THREAD

**Issue by TofPlay** [C4Q/AC3.2-Server-Side-Swift-Vapor#1]
Hi,
Interesting intro for Vapor 👍 🙂
Vapor 2 is now available
Do you plan to update your doc?

**Comment by spacedrabbit** [comment]
@TofPlay Happy you found it useful!
Eventually, but not currently a priority. The [second part](https://github.com/C4Q/AC3.2-Server-Side-Swift-Vapor-II) of this lesson looks at some of the changes needed to be made in the `Cat` model, but not in the entire project. All further repos on Vapor are written based on 2.0.

I'd recommend joining the [Vapor Slack](http://vapor.team/), they've been posting v1.5->2.0 migration guides
